version: "3"
services:
  library-service:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      SPRING_PROFILES_ACTIVE: 'system-test'
    ports:
      - "8085:8085"
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 8085 || exit 1" ]